import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import MoviePoster from "~/components/MoviePoster";
import MoviePosterPlaceholder from "~/components/MoviePosterPlaceholder";
import Pagination from "~/components/Pagination";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [pageOffset, setPageOffset] = useState(0);
  const user = useUser();
  const popularMoviesQuery = api.tmdb.getPopularMovies.useQuery({
    pageOffset,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-slate-900  text-white">
        <div className="mx-auto max-w-7xl">
          {user.isSignedIn && <SignOutButton />}
          {!user.isSignedIn && <SignInButton />}
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
            {popularMoviesQuery.isLoading || popularMoviesQuery.isFetching ? (
              <>
                {[...new Array(20).keys()].map((_, index) => (
                  <MoviePosterPlaceholder key={index} />
                ))}
              </>
            ) : (
              <>
                {popularMoviesQuery.data?.results.map((movie) => (
                  <MoviePoster key={movie.id} {...movie} />
                ))}
              </>
            )}
          </div>
          <div className="py-8">
            {popularMoviesQuery.data && (
              <Pagination
                pageOffset={pageOffset}
                setPageOffset={setPageOffset}
                isPreviousData={popularMoviesQuery.isPreviousData}
                totalPages={popularMoviesQuery.data.total_pages}
              />
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
