import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import MoviePoster from "~/components/MoviePoster";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const popularMoviesQuery = api.tmdb.getPopularMovies.useQuery({
    pageOffset: 0,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-slate-900  text-white">
        <div className="mx-auto max-w-7xl">
          {user.isSignedIn && <SignOutButton />}
          {!user.isSignedIn && <SignInButton />}
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
            {popularMoviesQuery.data?.results.map((movie) => (
              <MoviePoster key={movie.id} {...movie} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
